package emma.mapper.mapobj.resources;

import emma.mapper.Mapping;
/**
 * Generated by the Mapping process from Petri S resources
 * @author pierrotws
 *
 */
public class S extends emma.petri.model.resources.S implements MappedResource {
	
	public S(emma.petri.model.resources.S unmapped, Mapping m){
		super(unmapped.getName());
	}
}
